In [2]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,NaN,NaN,NaN,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,NaN,NaN,NaN,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,NaN,NaN,NaN,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,NaN,NaN,NaN,KPMG France,NaN,NaN
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,NaN,NaN,NaN,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [6]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [7]:
df_altered = df_original

In [8]:
df_altered.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [10]:
median_salary = df_altered['salary_year_avg'].median()

median_salary

np.float64(115000.0)

In [11]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [12]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [14]:
id(df_original)
id(df_altered)

2029036185680

In [26]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [27]:
df_altered = df_original.copy()

In [29]:
df_cleaned = df_altered.dropna(subset=['salary_year_avg'])

df_cleaned.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."

In [32]:
df_data = df_original

In [37]:
df_new = df_data.sample(frac=.1)

df_new

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
427114,Senior Data Analyst,Senior Data Analyst,Dubai - United Arab Emirates,via Ai-Jobs.net,Full-time,False,United Arab Emirates,2023-02-09 16:42:00,False,False,United Arab Emirates,year,98500.0,NaN,CAFU,['sql'],{'programming': ['sql']}
262669,Data Scientist,Data Scientist,"Atlanta, GA",via Ladders,Full-time,False,"Illinois, United States",2023-05-13 07:23:01,False,False,United States,year,125000.0,NaN,Insight Global,"['python', 'sql', 'r', 'scala', 'java', 'c++',...","{'analyst_tools': ['sas', 'tableau', 'power bi..."
264516,Data Scientist,"Data Scientist (Atlanta, GA)","Atlanta, GA",via Built In,Full-time,False,"Illinois, United States",2023-05-12 07:05:36,False,True,United States,NaN,NaN,NaN,Elevance Health,"['go', 'python', 'r', 'sas', 'sas', 'hadoop']","{'analyst_tools': ['sas'], 'libraries': ['hado..."
497345,Data Analyst,Data Analyst,"Santa Barbara, CA",via Trabajo.org,Full-time,False,"California, United States",2023-09-02 11:00:50,False,False,United States,NaN,NaN,NaN,Montecito Bank & Trust,"['sql', 'r', 'tableau', 'word', 'excel', 'powe...","{'analyst_tools': ['tableau', 'word', 'excel',..."
436379,Data Analyst,Data Analyst,"Doha, Qatar",via Jobs Trabajo.org,Full-time,False,Qatar,2023-10-16 16:52:09,False,False,Qatar,NaN,NaN,NaN,Work corp,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726360,Data Engineer,Data Engineer/ ETL Informatica,"Jersey City, NJ",via Dice,Full-time,False,"New York, United States",2023-01-13 21:08:14,True,False,United States,year,145000.0,NaN,"Stamford Technology Solutions LLC, DBA Infinity","['python', 'shell', 'oracle', 'azure', 'aws', ...","{'cloud': ['oracle', 'azure', 'aws'], 'os': ['..."
487669,Data Engineer,Staff Data Engineer,"Greater London, UK",via WANE Jobs,Full-time,False,United Kingdom,2023-02-14 11:32:08,False,False,United Kingdom,NaN,NaN,NaN,BP,"['python', 'go', 'java', 'c++', 'sql', 'nosql'...","{'libraries': ['pandas', 'seaborn', 'spark'], ..."
238770,Data Engineer,Sr. Data Engineer,Anywhere,via LinkedIn,Full-time,True,"Florida, United States",2023-02-08 15:09:46,False,True,United States,NaN,NaN,NaN,(ISSA) International Sports Sciences Association,"['sql', 'mongodb', 'mongodb', 'shell', 'bash',...","{'async': ['jira'], 'cloud': ['azure', 'snowfl..."
531186,Senior Data Engineer,Senior Data Engineer,"Kansas City, MO",via Eight Eleven Group,Full-time,False,"Illinois, United States",2023-04-15 19:08:13,False,False,United States,NaN,NaN,NaN,Brooksource,"['python', 'sql', 'java', 'scala', 'c#', 'c', ...","{'cloud': ['databricks', 'azure', 'aws', 'snow..."
75650,Data Engineer,"Solutions Engineer, Data & Analytics","New Bandon, NB, Canada",via JobServe,Full-time,False,Canada,2023-10-07 00:18:12,True,False,Canada,NaN,NaN,NaN,Sapiens,NaN,NaN

In [38]:
df_alterted = df.copy()

In [52]:
median_salary = df_altered['salary_year_avg'].median()

df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [51]:
median_salary

np.float64(115000.0)